export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_STREAM = 'CREATE_STREAM';
export const FETCH_MULTIPLE_STREAMS = 'FETCH_MULTIPLE_STREAMS';
export const FETCH_SINGLE_STREAM = 'FETCH_SINGLE_STREAM';
export const DELETE_STREAM = 'DELETE_STREAM';
export const EDIT_STREAM = 'EDIT_STREAM';